# Generated by Django 4.1.3 on 2022-11-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "zone",
                    models.TextField(
                        blank=True, null=True, verbose_name="Тарифная зона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Станция",
                "verbose_name_plural": "Станции",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер поезда")),
                (
                    "train_type",
                    models.TextField(blank=True, null=True, verbose_name="Тип поезда"),
                ),
                (
                    "vagon_number",
                    models.IntegerField(verbose_name="Количество вагонов"),
                ),
            ],
            options={
                "verbose_name": "Поезд",
                "verbose_name_plural": "Поезда",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_list",
                    models.TextField(
                        blank=True, null=True, verbose_name="Список станций"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Отправление"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Прибытие"
                    ),
                ),
                (
                    "end_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="test.train",
                        verbose_name="Поезд",
                    ),
                ),
                (
                    "start_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="test.station",
                        verbose_name="Начальная станция",
                    ),
                ),
            ],
            options={
                "verbose_name": "График движения",
                "verbose_name_plural": "График движения",
                "ordering": ["-id"],
            },
        ),
    ]
